# SPDX-License-Identifier: Apache-2.0 OR GPL-2.0
#
# YukiZygisk - Kernel build rules for the standalone LKM.
#
# License: Author's work under Apache-2.0; when used as a kernel module
# (or linked with the Linux kernel), GPL-2.0 applies for kernel compatibility.
#
# Author: Anatdx

obj-m += yukizygisk.o

yukizygisk-objs := \
	core/module.o \
	core/control.o \
	host/runtime.o \
	host/root_impl.o \
	host/patch_text.o \
	host/lsm.o \
	host/adapter.o \
	feature/zygote_probe.o \
	feature/zygote_orch.o \
	feature/zygote_nl.o \
	feature/zygote_ctl.o

ccflags-y += -I$(src)
ccflags-y += -Wno-declaration-after-statement
ccflags-y += -Wno-missing-braces
ccflags-y += -Wno-unused-function
ccflags-y += -Wno-unused-variable
